"""new models

Revision ID: d260a188c362
Revises: 
Create Date: 2019-04-02 07:24:19.829708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd260a188c362'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defender', schema=None) as batch_op:
        batch_op.create_foreign_key('player_id', 'player', ['player_id'], ['id'])

    with op.batch_alter_table('forward', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('player_id', 'player', ['player_id'], ['id'])

    with op.batch_alter_table('goalkeeper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aerial', sa.Float(precision=2), nullable=True))

    with op.batch_alter_table('midfielder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('player_id', 'player', ['player_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('midfielder', schema=None) as batch_op:
        batch_op.drop_constraint('player_id', type_='foreignkey')
        batch_op.drop_column('player_id')

    with op.batch_alter_table('goalkeeper', schema=None) as batch_op:
        batch_op.drop_column('aerial')

    with op.batch_alter_table('forward', schema=None) as batch_op:
        batch_op.drop_constraint('player_id', type_='foreignkey')
        batch_op.drop_column('player_id')

    with op.batch_alter_table('defender', schema=None) as batch_op:
        batch_op.drop_constraint('player_id', type_='foreignkey')

    # ### end Alembic commands ###
